// DO NOT EDIT this file - it is generated by the build
namespace ButtPlugin.Core
{
    internal static class ButtPluginVersionInfo
    {
        internal const string Version = @"1.0.0.0";
    }
}
