name: "[Reusable] Build"

on:
  workflow_call:
    inputs:
      version:
        description: "Build version (major.minor.patch, without the v)"
        required: true
        type: string

jobs:
  build:
    runs-on: windows-2022
    timeout-minutes: 10

    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true

    defaults:
      run:
        working-directory: src

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Enable .NET Framework 3.5
        run: DISM /Online /Enable-Feature /FeatureName:NetFx3 /All

      - name: Setup MSBuild path
        uses: microsoft/setup-msbuild@v1.1
        with:
          vs-version: "[17.0,)"

      - name: Build and Publish
        run:
          msbuild LoveMachine.sln /r /p:Configuration=Release /p:DeployOnBuild=true
          /p:PublishProfile=FolderProfile /p:Version=${{ inputs.version }}

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: bin
          path: src/bin
