name: "[Reusable] Test report"

on:
  workflow_call:
    inputs:
      pull_request_number:
        description: The pull request number if applicable
        required: false
        type: string

jobs:
  report:
    runs-on: ubuntu-latest

    steps:
      - name: Download test results
        uses: actions/download-artifact@v4
        with:
          name: results
          path: results

      - name: Generate test report
        uses: joonvena/robotframework-reporter-action@229b6d4248b20be6e54f4fc32c7414130d1bf200 # v2.5
        with:
          gh_access_token: ${{ secrets.GITHUB_TOKEN }}
          report_path: results
          pull_request_id: ${{ inputs.pull_request_number }}
