[CustomMessages]
KK=コイカツ！
KKS=コイカツ！サンシャイン
HS2=ハニーセレクト2
PH=プレイホーム
AGH=奉課後輪姦中毒
IO=インサルトオーダー
COM3D2=カスタムオーダーメイド3D2
InstallIntiface=LoveMachineを使用するにはIntifaceをインストールする必要があります。今インストールしますか？
SelectPathTitle=インストール先・%dページ
SelectPath=インストール先のゲームフォルダを選択してください。持っていないゲームの入力欄は空白のままにしておいてください。
NotAGameDir=「%s」はUnityゲームフォルダじゃないみたいです。ゲームデータを含むフォルダを選択してください。
